apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "resource.default.name" $ }}-migrate-aws-apps-mc
  namespace: org-giantswarm
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames:
  - {{ .Values.global.managementCluster }}-kubeconfig
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "resource.default.name" $ }}-migrate-aws-apps-mc
  namespace: org-giantswarm
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "resource.default.name" $ }}-migrate-aws-apps-mc
subjects:
- kind: ServiceAccount
  name: {{ include "resource.default.name" $ }}-migrate-aws-apps
  namespace: {{ $.Release.Namespace }}
