{{- define "awsPodIdentityWebhookValuesDefault" }}
  aws:
    tokenAudience: {{ include "awsApiServerApiAudiences" $ | trim  }}
    region: {{ include "aws-region" $ | trim }}
{{- end }}
{{- $awsPodIdentityWebhookValues := (include "awsPodIdentityWebhookValuesDefault" $ ) | fromYaml -}}
{{- $customAwsPodIdentityWebhookValues := .Values.global.apps.awsPodIdentityWebhook.values -}}
{{- if $customAwsPodIdentityWebhookValues -}}
{{- $awsPodIdentityWebhookValues = mergeOverwrite $awsPodIdentityWebhookValues (deepCopy $customAwsPodIdentityWebhookValues) -}}
{{- end -}}
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: {{ include "resource.default.name" . }}-aws-pod-identity-webhook
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- include "labels.common" . | nindent 4 }}
spec:
  {{- $_ := set $ "appName" "aws-pod-identity-webhook" }}
  url: oci://gsoci.azurecr.io/charts/giantswarm/aws-pod-identity-webhook
  ref:
    tag: "{{ include "cluster.app.version" $ }}"
  interval: 1h
  timeout: 60s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" . }}-aws-pod-identity-webhook
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: aws-pod-identity-webhook
  targetNamespace: kube-system
  storageNamespace: kube-system
  chartRef:
    kind: OCIRepository
    name: {{ include "resource.default.name" . }}-aws-pod-identity-webhook
  dependsOn:
    - name: {{ include "resource.default.name" . }}-cert-manager
      namespace: {{ .Release.Namespace }}
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" . }}-kubeconfig
  interval: 5m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  {{- if $awsPodIdentityWebhookValues }}
  values: {{- $awsPodIdentityWebhookValues | toYaml | nindent 4 }}
  {{- end }}
  valuesFrom:
  - kind: ConfigMap
    name: {{ include "resource.default.name" . }}-cluster-values
    valuesKey: values
    optional: false
  {{- if .Values.global.apps.awsPodIdentityWebhook.extraConfigs }}
  {{- range .Values.global.apps.awsPodIdentityWebhook.extraConfigs }}
  - kind: {{ .kind }}
    name: {{ .name }}
    valuesKey: values
    optional: {{ .optional | default false }}
  {{- end }}
  {{- end }}
