apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: {{ include "resource.default.name" . }}-aws-ebs-csi-driver-smons
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- include "labels.common" . | nindent 4 }}
spec:
  {{- $_ := set $ "appName" "aws-ebs-csi-driver-servicemonitors" }}
  url: oci://gsoci.azurecr.io/charts/giantswarm/aws-ebs-csi-driver-servicemonitors
  ref:
    tag: "{{ include "cluster.app.version" $ }}"
  interval: 1h
  timeout: 60s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" . }}-aws-ebs-csi-driver-smons
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: aws-ebs-csi-driver-servicemonitors
  targetNamespace: kube-system
  storageNamespace: kube-system
  chartRef:
    kind: OCIRepository
    name: {{ include "resource.default.name" . }}-aws-ebs-csi-driver-smons
  dependsOn:
    - name: {{ include "resource.default.name" . }}-prometheus-operator-crd
      namespace: {{ .Release.Namespace }}
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" . }}-kubeconfig
  interval: 5m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: {{ include "resource.default.name" . }}-cluster-values
    valuesKey: values
    optional: false
  {{- if .Values.global.apps.awsEbsCsiDriverServiceMonitors.extraConfigs }}
  {{- range .Values.global.apps.awsEbsCsiDriverServiceMonitors.extraConfigs }}
  - kind: {{ .kind }}
    name: {{ .name }}
    valuesKey: values
    optional: {{ .optional | default false }}
  {{- end }}
  {{- end }}
