{{ if (include "useCertManagerDnsChallenges" $ | eq "true") }}
{{- $_ := set $ "appName" "cert-manager-crossplane-resources" }}
{{- /* Check if app is in Release CR */}}
{{- if include "cluster.app.in-release" $ | eq "true" }}
{{- $resourceName := printf "%s-cert-manager-crossplane-resources" (include "resource.default.name" $) }}
{{- $truncatedResourceName := trunc 53 $resourceName }}
apiVersion: v1
data:
  values: |
    clusterName: {{ include "resource.default.name" $ }}
    # Configure the AWS provider
    providers:
      aws:
        enabled: true
        accountID: {{ include "aws-account-id" $ | quote }}
        partition: {{ include "aws-partition" $ }}
        region: {{ include "aws-region" $ }}
        oidc:
          # Construct OIDC domain based on cluster name and base domain
          {{- if hasPrefix "cn-" (include "aws-region" .) }}
          # For Chinese regions, extract just the domain part without https://
          domain: "s3.{{ include "aws-region" . }}.amazonaws.com.cn/{{ include "aws-account-id" .}}-g8s-{{ include "resource.default.name" $ }}-oidc-pod-identity-v3"
          {{- else }}
          # For non-Chinese regions
          domain: "irsa.{{ include "resource.default.name" $ }}.{{ .Values.global.connectivity.baseDomain }}"
          {{- end }}
        serviceType: managed
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $truncatedResourceName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $truncatedResourceName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  url: oci://gsoci.azurecr.io/charts/giantswarm/cert-manager-crossplane-resources
  ref:
    tag: "{{ include "cluster.app.version" $ }}"
  interval: 1h
  timeout: 60s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $truncatedResourceName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  releaseName: {{ $truncatedResourceName }}
  targetNamespace: {{ $.Release.Namespace }}
  storageNamespace: {{ $.Release.Namespace }}
  chartRef:
    kind: OCIRepository
    name: {{ $truncatedResourceName }}
  serviceAccountName: automation
  interval: 5m
  install:
    timeout: 10m
    remediation:
      retries: -1
  upgrade:
    timeout: 10m
    remediation:
      retries: -1
  valuesFrom:
    # See above
    - kind: ConfigMap
      name: {{ $truncatedResourceName | quote }}
      valuesKey: values
      optional: false
    # Created by aws-crossplane-cluster-config-operator once the cluster gets provisioned
    - kind: ConfigMap
      name: {{ printf "%s-crossplane-config" (include "resource.default.name" $) | quote }}
      valuesKey: values
      optional: false
{{- end }}
{{- end }}
