{{- if eq .Values.global.connectivity.cilium.ipamMode "eni" }}
apiVersion: v1
data:
  values: |
    aws_eni_mode:
      enabled: true
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ printf "%s-cilium-crossplane-resources" (include "resource.default.name" $) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ printf "%s-cilium-crossplane-resources" (include "resource.default.name" $) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  {{- $_ := set $ "appName" "cilium-crossplane-resources" }}
  url: oci://gsoci.azurecr.io/charts/giantswarm/cilium-crossplane-resources
  ref:
    tag: "{{ include "cluster.app.version" $ }}"
  interval: 1h
  timeout: 60s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ printf "%s-cilium-crossplane-resources" (include "resource.default.name" $) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  releaseName: {{ printf "%s-cilium-crossplane-resources" (include "resource.default.name" $) }}
  targetNamespace: {{ $.Release.Namespace }}
  storageNamespace: {{ $.Release.Namespace }}
  chartRef:
    kind: OCIRepository
    name: {{ printf "%s-cilium-crossplane-resources" (include "resource.default.name" $) }}
  serviceAccountName: automation
  interval: 5m
  install:
    timeout: 10m
    remediation:
      retries: -1
  upgrade:
    timeout: 10m
    remediation:
      retries: -1
  valuesFrom:
    # See above
    - kind: ConfigMap
      name: {{ printf "%s-cilium-crossplane-resources" (include "resource.default.name" $) | quote }}
      valuesKey: values
      optional: false
    # Created by aws-crossplane-cluster-config-operator once the cluster gets provisioned
    - kind: ConfigMap
      name: {{ printf "%s-crossplane-config" (include "resource.default.name" $) | quote }}
      valuesKey: values
      optional: false
{{- end }}
