global:
  release:
    version: 29.1.0
  metadata:
    name: test-wc
    organization: "test"
  connectivity:
    baseDomain: example.com
  nodePools:
    pool0:
      type: machinepool
      maxSize: 2
      minSize: 2
      instanceTypeOverrides:
        - r6i.xlarge
        - m5.xlarge
  providerSpecific:
    region: "eu-west-1"
    awsAccountId: "123456789012"
  managementCluster: test

internal:
  awsPartition: "aws"

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
